CREATE TABLE Usuarios (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(15),
    email VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    isAdmin NUMBER(1, 0) DEFAULT 0 not null
);
CREATE TABLE Planos (
    id_plano INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeFantasia VARCHAR(255) NOT NULL,
    tipoPlano VARCHAR(255) NOT NULL,
    dataInicio DATE NOT NULL,
    dataFinal DATE NOT NULL
);
CREATE TABLE Produtos (
    id_produto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL
);
CREATE TABLE ProdutosPlano (
    id_produtoPlano INT GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
    id_produto INT,
    id_plano INT,
    valorTotal number(10, 2) not null,
    FOREIGN KEY (id_produto) REFERENCES Produtos (id_produto),
    FOREIGN KEY (id_plano) REFERENCES Planos (id_plano)
);
CREATE TABLE EmpresaClientes (
    id_empresaCliente INT GENERATED BY DEFAULT AS IDENTITY,
    cnpj VARCHAR(18) UNIQUE NOT NULL,
    nomeFantasia VARCHAR(255) NOT NULL,
    id_cliente INT,
    PRIMARY KEY (id_empresaCliente),
    FOREIGN KEY (id_cliente) REFERENCES Usuarios (id_usuario)
);
CREATE TABLE Contratos (
    id_contrato INT GENERATED BY DEFAULT AS IDENTITY,
    id_empresa_cliente INT,
    id_produto_plano INT,
    tipoPlano VARCHAR(255) NOT NULL,
    PRIMARY KEY(
        id_contrato,
        id_empresa_cliente,
        id_produto_plano
    ),
    FOREIGN KEY (id_empresa_cliente) REFERENCES EmpresaClientes (id_empresaCliente),
    FOREIGN KEY (id_produto_plano) REFERENCES ProdutosPlano (id_produtoPlano)
);
/* MYSQL */
create database salesforce;
use salesforce;
CREATE TABLE Usuarios (
    id_usuario INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(15),
    email VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    isAdmin TINYINT(1) DEFAULT 0 NOT NULL
);
CREATE TABLE Planos (
    id_plano INT AUTO_INCREMENT PRIMARY KEY,
    nomeFantasia VARCHAR(255) NOT NULL,
    tipoPlano VARCHAR(255) NOT NULL,
    dataInicio DATE NOT NULL,
    dataFinal DATE NOT NULL,
    valor DECIMAL(10, 2) NOT NULL
);
CREATE TABLE Produtos (
    id_produto int AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    preco double NOT NULL
);
CREATE TABLE ProdutosPlano (
    id_produtoPlano INT AUTO_INCREMENT PRIMARY KEY,
    id_produto INT,
    id_plano INT,
    FOREIGN KEY (id_produto) REFERENCES Produtos (id_produto),
    FOREIGN KEY (id_plano) REFERENCES Planos (id_plano)
);
CREATE TABLE EmpresaClientes (
    id_empresaCliente INT AUTO_INCREMENT PRIMARY KEY,
    cnpj VARCHAR(18) UNIQUE NOT NULL,
    telefone VARCHAR(15),
    razaoSocial VARCHAR(255) NOT NULL,
    nomeFantasia VARCHAR(255) NOT NULL,
    tamanho INT,
    id_cliente INT,
    FOREIGN KEY (id_cliente) REFERENCES Usuarios (id_usuario)
);
CREATE TABLE Enderecos (
    id_endereco INT AUTO_INCREMENT PRIMARY KEY,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    cep VARCHAR(10) NOT NULL,
    id_usuario INT,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios (id_usuario) ON DELETE CASCADE
);
CREATE TABLE Contratos (
    id_contrato INT AUTO_INCREMENT PRIMARY KEY,
    id_empresa_cliente INT,
    id_produto_plano INT,
    tipoPlano VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_empresa_cliente) REFERENCES EmpresaClientes (id_empresaCliente),
    FOREIGN KEY (id_produto_plano) REFERENCES ProdutosPlano (id_produtoPlano)
);